### ISSUE TITLE
Choppy audio in BlueVoice when connected to Bose bluetooth speakers.

### ISSUE THREAD

**Issue by raviam** [STMicroelectronics/BlueSTSDK_GUI_iOS#2]
Hi!

I've used iPhone 7,8 and XS where the phone is connected to a bluetooth speaker. When I go into the BlueVoice screen, the audio lags a lot, is extremely choppy and there is a lot of packet loss. I observed this problem only on iOS devices. The Google Pixel 3 worked fine.

**Comment by GiovanniVisentini** [comment]
Hi Reviam,

could you open the issue here:
https://github.com/STMicroelectronics/BlueSTSDK_iOS the repository of the I/O library
or here: https://github.com/STMicroelectronics/STBlueMS_iOS the repository of the ST BLE Sensor app

and explain better your setup? do you have a microphone -> blueVoice -> iPhone -> speaker? 

Thanks
Giovanni

**Comment by raviam** [comment]
Sure. Thanks! Here's the issue in the ST BLE Sensor app repository. (https://github.com/STMicroelectronics/STBlueMS_iOS/issues/8 )
